version: '3.9'

services:
  mysql-db:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASS
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

  app:
    depends_on:
      - mysql-db
    restart: on-failure
    image: car-sharing:latest
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{"spring.datasource.url":"jdbc:mysql://mysql-db:3306/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC",
      "spring.datasource.username":"$MYSQLDB_USER",
      "spring.datasource.password":"$MYSQLDB_ROOT_PASS",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
      "spring.jpa.hibernate.ddl-auto" : "validate"}'
      TOKEN_SIGNING_KEY: ${TOKEN_SIGNING_KEY}
      telegram.bot.name: ${BOT_NAME}
      telegram.bot.token: ${BOT_TOKEN}
